// Generated by https://quicktype.io

class DireccionModel {
  String direccion;

  DireccionModel({
    this.direccion,
  });
   DireccionModel.fromJsonMap(Map<String, dynamic> json) {
    direccion=json['direccion'];

  }
}
