// Generated by https://quicktype.io
import 'package:flutter_application_1/models/usuarioModel.dart';
import 'dart:convert';

class Historialenviados {
  List platos;
  String nombre;
  String id;
  int valor;
  UsuarioModel usuarioId;
  String estado;
  String direccionId;
  String fecha;
  int numero;


  Historialenviados({
    this.nombre,
    this.platos,
    this.id,
    this.valor,
    this.usuarioId,
    this.estado,
    this.direccionId,
    this.fecha,
    this.numero,
  });

  Historialenviados.fromJsonMap(Map<String, dynamic> json) {
     platos = json['platos'];
    nombre= json["nombre"] ;
    id = json['_id'];
    valor = json['valor'];
    usuarioId = UsuarioModel.fromJsonMap(json['usuario_id']);
    estado = json['estado'];
    direccionId = json['direccion_id'];
    fecha = json['fecha'];
    numero = json['numero'];
  }
}

class Categorias {
  // ignore: deprecated_member_use
  final List<Historialenviados> categorys = new List();
  Categorias();
  Categorias.fromJsonList(List<dynamic> jsonList) {
    if (jsonList == null) return;

    for (var item in jsonList) {
      final category = new Historialenviados.fromJsonMap(item);
      categorys.add(category);
    }
  }
}

