// Generated by https://quicktype.io



import 'package:flutter_application_1/models/direccionModel.dart';
import 'package:flutter_application_1/models/usuarioModel.dart';

class Historialpedidos {
  DireccionModel direccion;
  List platos;
  String nombre;
  String id;
  int valor;
  UsuarioModel usuarioId;
  String estado;
  String direccionId;
  String fecha;
  int numero;


  Historialpedidos({
    this.direccion,
    this.nombre,
    this.platos,
    this.id,
    this.valor,
    this.usuarioId,
    this.estado,
    this.direccionId,
    this.fecha,
    this.numero,
  });

  Historialpedidos.fromJsonMap(Map<String, dynamic> json) {
    direccion=DireccionModel.fromJsonMap(json['direccion_id']);
    platos = json['platos'];
    nombre= json["nombre"] ;
    id = json['_id'];
    valor = json['valor'];
    usuarioId = UsuarioModel.fromJsonMap(json['usuario_id']);
    estado = json['estado'];
    fecha = json['fecha'];
    numero = json['numero'];
  }
}

class Pedido {
  // ignore: deprecated_member_use
  final List<Historialpedidos> pedido = new List();
 Pedido();
  Pedido.fromJsonList(List<dynamic> jsonList) {
    if (jsonList == null) return;

    for (var item in jsonList) {
      final category = new Historialpedidos.fromJsonMap(item);
      pedido.add(category);
    }
  }
}

