// Generated by https://quicktype.io

import 'loginModals.dart';

class UsuarioModel {
  String id;
  String nombre;
  String apellidos;
  int numero;

  UsuarioModel({
    this.id,
    this.nombre,
    this.apellidos,
    this.numero,
  });


    UsuarioModel.fromJsonMap(Map<String, dynamic> json) {
    id=json['_id'];
    nombre=json['nombre'];
    apellidos=json['apellidos'];
    numero=json['numero'];
  }
}


